version: '3'
services:
  db:
    restart: always
    image: postgres:10.3
    environment:
      - POSTGRES_USER=govoteuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=GoVoteGSO
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  govote:
    restart: always
    build: .
    ports: 
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=GoVoteGSO
      - DB_USER=govoteuser
      - DB_PASS=password
      - DB_PORT=5432